version: "3.7"

services:
  wexpt-db:
    build:
      context: .
      dockerfile: ./docker-config/db/Dockerfile
    container_name: wexpt-db
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wexptnetwork

  wexpt-app:
    build:
      context: .
      dockerfile: ./docker-config/app/Dockerfile
    container_name: wexpt-app
    env_file:
      - .env
    depends_on:
      - wexpt-db
    ports:
      - "${APP_PORT}:2984"
    networks:
      - wexptnetwork

networks:
  wexptnetwork:

volumes:
  database_data: