version: "3.7"

services:
  wexptdb:
    build:
      context: .
      dockerfile: ./docker-config/db/Dockerfile
    container_name: wexptdb
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wexptnetwork

  wexptapp:
    build:
      context: .
      dockerfile: ./docker-config/app/Dockerfile
    container_name: wexptapp
    env_file:
      - .env
    depends_on:
      - wexptdb
    ports:
      - "${APP_PORT}:2984"
    networks:
      - wexptnetwork

networks:
  wexptnetwork:

volumes:
  database_data: