server:
  error:
    include-stacktrace: always
  port: 2984

spring:
  application:
    name: ${APP_NAME:wexpt_app}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:wexptdb}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found=true:
